// Code generated by Slice Machine. DO NOT EDIT.

import { defineAsyncComponent } from "vue";
import { defineSliceZoneComponents } from "@prismicio/vue";

export const components = defineSliceZoneComponents({
  duet_content: defineAsyncComponent(() => import("./DuetContent/index.vue")),
  hero_banner: defineAsyncComponent(() => import("./HeroBanner/index.vue")),
  testimonials: defineAsyncComponent(() => import("./Testimonials/index.vue")),
});
